service: batch
runtime: go
api_version: go1.9
handlers:
- url: /job/.*
  script: _go_app
  secure: always

env_variables:
  CRYPTO_COMPARE_ENDPOINT: https://min-api.cryptocompare.com/data/pricemulti
  FIREBASE_ADMIN_KEY: /Users/akiho/.firebase/crypto-assistant-dev-firebase-adminsdk-eeusr-12a9467b10.json
  RTDB_URL: https://crypto-assistant-dev.firebaseio.com/

skip_files:
- .*vendor
- .*rpc
- .*dbs
- .*.idea
- .*project-name-having-too-many-files
- .*functions
